apiVersion: v1
kind: Pod
metadata:
  name: s3-pod
spec:
  containers:
    - name: app-container
      image: umar7867/todo
      volumeMounts:
        - mountPath: /mnt/s3
          name: s3-storage
  volumes:
    - name: s3-storage
      persistentVolumeClaim:
        claimName: s3-pvc
