apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - allow_other
  flexVolume:
    driver: "s3fs"
    options:
      bucket: pvpvc15
      url: https://ap-south-1.console.aws.amazon.com
    #  access-key: YOUR_AWS_ACCESS_KEY
    # secret-key: YOUR_AWS_SECRET_KEY

